version: "3"
services:
        tomcat:
                build:
                        context: "."
                        dockerfile: "Dockerfile"
                ports:
                        - "8787:8080"
